name: Build gatling

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      build-config:
        required: true
        type: string
      # Must match CI installation path (see USD issue #1025)
      usd-download-url:
        required: true
        type: string
      usd-install-path:
        required: true
        type: string
      upload-archive:
        required: false
        type: boolean
        default: false
      archive-name:
        required: true
        type: string
      archive-file-name:
        required: false
        type: string
      mdl-sdk-cache-key:
        required: true
        type: string
      cmake-params:
        required: false
        type: string
      houdini-packaging:
        required: false
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build gatling
    runs-on: ${{ inputs.image }}

    env:
      mdl-sdk-dir: "MDL-SDK/INSTALL"

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install packages
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository ppa:kisak/kisak-mesa
        sudo apt update
        sudo apt upgrade
        sudo apt-get install mesa-utils xvfb qt5-default libgl1-mesa-dev libvulkan-dev vulkan-tools mesa-vulkan-drivers

    - name: List mesa/vulkan files
      run: |
        dpkg -L mesa-utils
        dpkg -L libgl1-mesa-dev
        dpkg -L libvulkan-dev
        dpkg -L mesa-vulkan-drivers
        tree /usr/lib
        tree /usr/local/lib

    - name: Set up environment variables (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "LD_LIBRARY_PATH=${{ inputs.usd-install-path }}/lib" >> $GITHUB_ENV
        echo "DISPLAY=:1" >> $GITHUB_ENV
        echo "VK_LOADER_DEBUG=all" >> $GITHUB_ENV
        echo "LIBGL_ALWAYS_SOFTWARE=1" >> $GITHUB_ENV
        echo "GALLIUM_DRIVER=llvmpipe" >> $GITHUB_ENV

    - name: Start virtual framebuffer
      run: |
        Xvfb :1 -screen 0 1280x960x24 &

    - name: Test glxinfo
      run: glxinfo

    - name: Test vulkaninfo
      run: vulkaninfo

    - name: Fetch USD binaries
      run: curl ${{ inputs.usd-download-url }} -L -v -o USD.tar.gz

    - name: Unpack USD binaries
      run: mkdir -p ${{ inputs.usd-install-path }} && tar -xvf USD.tar.gz -C ${{ inputs.usd-install-path }}

    # We need to put the USD libs in the PATH because we build against USD's MaterialX
    # distribution. The libs are shared and loaded for gi_test's ctest discovery.
    - name: Set up USD environment variables (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "${{ inputs.usd-install-path }}/lib" >> $GITHUB_PATH
        echo "${{ inputs.usd-install-path }}/bin" >> $GITHUB_PATH

    - name: Create temporary folders
      run: mkdir BUILD INSTALL

    - name: Restore MDL SDK
      id: restore-mdl-sdk
      uses: actions/cache/restore@v4
      with:
        path: "${{ env.mdl-sdk-dir }}"
        key: ${{ inputs.mdl-sdk-cache-key }}
        fail-on-cache-miss: true

    - name: Install NASM
      if: runner.os == 'Windows'
      uses: ilammy/setup-nasm@v1.4.0

    - name: Generate build system files using CMake
      working-directory: BUILD
      run: |
        cmake .. \
          -DUSD_ROOT=${{ inputs.usd-install-path }} \
          -DMDL_ROOT=../${{ env.mdl-sdk-dir }} \
          -DCMAKE_BUILD_TYPE=${{ inputs.build-config }} \
          -DCMAKE_INSTALL_PREFIX="$PWD/../INSTALL" \
          ${{ inputs.cmake-params }}

    - name: Build gatling
      working-directory: BUILD
      run: cmake --build . --config ${{ inputs.build-config }} -j 2 --target hdGatling gatling gi_test hdGatling_test

    - name: Install gatling
      working-directory: BUILD
      run: cmake --install . --config ${{ inputs.build-config }} --component hdGatling

    - name: Run tests
      working-directory: BUILD
      run: ./bin/hdGatling_test

    - name: Package for Houdini
      if: inputs.houdini-packaging
      working-directory: INSTALL
      run: |
        mkdir -p dso/usd
        mkdir -p dso/usd_plugins
        mkdir -p soho/parameters
        cp ../dist/houdini/UsdRenderers.json .
        cp ../dist/houdini/HdGatlingRendererPlugin_Viewport.ds soho/parameters/
        cp ../dist/houdini/plugInfo.json dso/usd_plugins/
        mv hdGatling dso/usd_plugins
        mv hdGatling* dso/usd

    - name: Create archive
      if: inputs.upload-archive
      working-directory: INSTALL
      run: tar -zcvf ${{ inputs.archive-file-name }} *

    - name: Upload archive
      if: inputs.upload-archive
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.archive-name }}
        path: INSTALL/${{ inputs.archive-file-name }}
        retention-days: 7
