name: Validation Build

on:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'wip/geomsubsets'
    paths-ignore:
      - '**.md'
      - '**.glsl'

jobs:
  build-mdl-sdk:
    name: Build MDL SDK
    uses: pablode/MDL-SDK/.github/workflows/main.yml@GA-2023.0.2
    with:
      cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}

  build-2211:
    name: Build gatling for USD v22.11 (Release)
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: "22.11"
      mdl-sdk-cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}

  build-2308:
    name: Build gatling for USD v23.08 (Release)
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: "23.08"
      mdl-sdk-cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}
